baseurl: https://silly-haupia-2459d1.netlify.app/
title: Plinth Analytics
author: Plinth Analytics
canonifyurls: yes
languagecode: en
paginate: 3
theme: hugo-renga
enableEmoji: yes
hasCJKLanguage: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
params:
  copyright: © 2022 Plinth Analytics
  copyrightUrl: https://silly-haupia-2459d1.netlify.app/
  email: info@plinthanalytics.com
  faviconfile: image/logo.png
  github: Plinth-Analytics
  highlightjs: yes
  linkedin: nathanieldphillips
  logofile: image/plinth_logo_vertical.png
  pagetitle: Plinth Analytics
  posts_navigation: yes
  progressively: no
  uselatex: yes
menu:
  primary:
    - identifier: home
      name: home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: products
      name: products
      url: /products/
      weight: 3
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 4
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 5


markup:
  goldmark:
    renderer:
      unsafe: true
